# Generated by Django 4.2 on 2023-04-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('img', models.ImageField(upload_to='banners', verbose_name='Баннер')),
            ],
            options={
                'verbose_name': 'Главные баннеры',
                'verbose_name_plural': 'Главные баннеры',
            },
        ),
    ]
