# Generated by Django 4.2 on 2023-04-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Главный баннер'),
        ),
    ]
