# Generated by Django 4.2 on 2023-04-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_banner_is_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Заголовок')),
                ('caption', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(default=300, verbose_name='Цена')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Время')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='events', verbose_name='Баннер (изображение)')),
                ('video', models.FileField(blank=True, null=True, upload_to='events', verbose_name='Баннер (видео)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tags', models.CharField(blank=True, default=None, help_text='Через пробел', max_length=200, null=True, verbose_name='Теги')),
                ('address', models.CharField(blank=True, default='ул.Гвардейская 2, "Таксопарк"', max_length=200, null=True, verbose_name='Теги')),
            ],
        ),
    ]
