# Generated by Django 4.2 on 2023-04-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_event_date_alter_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_complete',
            field=models.BooleanField(default=False, editable=False, verbose_name='Состоялось'),
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, default='ул.Гвардейская 2, "Таксопарк"', max_length=200, null=True, verbose_name='Адрес'),
        ),
    ]
