# Generated by Django 4.2 on 2023-05-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_event_is_complete_alter_event_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='message_id',
            field=models.IntegerField(blank=True, default=None, editable=False, null=True),
        ),
    ]
